revert: upgrade dependencies on push to this branch
This reverts commit 0b5c35f4ac3fb74c47aea90abe29722fe42fdd70.

diff --git a/.github/workflows/requirements-pr.yml b/.github/workflows/requirements-pr.yml
--- a/.github/workflows/requirements-pr.yml
+++ b/.github/workflows/requirements-pr.yml
@@ -3,12 +3,18 @@
 name: Requirements (PR)
 
 on:
-  push:
-    branches: [py39]
+  pull_request:
+    branches: [master]
+    types:
+      - opened
+      - synchronize
+      - reopened
+      - ready_for_review
 
 jobs:
   upgrade:
     name: Upgrade requirement files
+    if: github.event.pull_request.draft == false
     runs-on: ubuntu-20.04
     strategy:
       matrix:
@@ -23,11 +29,19 @@ jobs:
       - name: Check for modified dependencies
         id: git-diff
         run:
-          echo "::set-output name=dependency-changes::$(git diff origin/master
-          --name-only -- reqs setup.cfg)"
+          echo "::set-output name=dependency-changes::$(git diff
+          origin/$GITHUB_BASE_REF --name-only -- reqs setup.cfg)"
         # Also triggers on (unwanted) changes to requirements.txt files
       - name: Show dependency changes changes
-        run: git diff origin/master -- reqs/requirements*.in setup.cfg
+        run:
+          git diff origin/$GITHUB_BASE_REF -- reqs/requirements*.in setup.cfg
+      - name: Abort if fork PR and dependency changes
+        if:
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          steps.git-diff.outputs.dependency-changes != ''
+        run: |
+          echo "::error::Cannot modify package dependencies through a PR from a fork"
+          exit 1
       - name: Set up Python ${{ matrix.python-version }}
         if: steps.git-diff.outputs.dependency-changes != ''
         uses: actions/setup-python@master
@@ -48,13 +62,13 @@ jobs:
 
   push:
     name: Push changes
+    if: github.event.pull_request.draft == false
     runs-on: ubuntu-20.04
     needs:
       - upgrade
     steps:
       - uses: actions/checkout@v2
         with:
-          ref: py39
           token: ${{ secrets.PAT }}
       - uses: actions/download-artifact@v2
         with:
@@ -65,11 +79,12 @@ jobs:
           git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
           git config --global user.name ${{ github.actor }}
           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+          git checkout -b ${GITHUB_HEAD_REF}
           FILES_TO_COMMIT="reqs/*/requirements*.txt"
           if [[ $(git diff -- ${FILES_TO_COMMIT}) ]]; then
             git add ${FILES_TO_COMMIT}
             git commit -m "ci: upgrade developer dependencies (automatic)"
             git config pull.rebase true
-            git pull origin py39
-            git push origin py39
+            git pull origin ${GITHUB_HEAD_REF}
+            git push origin HEAD:${GITHUB_HEAD_REF}
           fi
