fix: abort upgrading if no dependency changes

diff --git a/.github/workflows/requirements-pr.yml b/.github/workflows/requirements-pr.yml
--- a/.github/workflows/requirements-pr.yml
+++ b/.github/workflows/requirements-pr.yml
@@ -12,7 +12,7 @@ on:
       - ready_for_review
 
 jobs:
-  requirements:
+  upgrade:
     name: Upgrade requirement files
     if: github.event.pull_request.draft == false
     runs-on: ubuntu-18.04
@@ -24,28 +24,35 @@ jobs:
           - 3.8
     steps:
       - uses: actions/checkout@v2
+      - run: git fetch origin
+      - name: Check for modified dependencies
+        id: git-diff
+        run:
+          echo "::set-output name=dependency-changes::$(git diff
+          origin/$GITHUB_BASE_REF --name-only -- reqs setup.cfg)"
+        # Also triggers on (unwanted) changes to requirements.txt files
+      - name: Show dependency changes changes
+        run:
+          git diff origin/$GITHUB_BASE_REF -- reqs/requirements*.in setup.cfg
+      - name: Abort if fork PR and dependency changes
+        if:
+          github.event.pull_request.head.repo.full_name != github.repository &&
+          steps.git-diff.outputs.dependency-changes != ''
+        run: |
+          echo "::error::Cannot modify package dependencies through a PR from a fork"
+          exit 1
       - name: Set up Python ${{ matrix.python-version }}
+        if: steps.git-diff.outputs.dependency-changes != ''
         uses: actions/setup-python@master
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
+        if: steps.git-diff.outputs.dependency-changes != ''
         run: |
           python -m pip install --upgrade pip
           pip install pip-tools
-      - name: Fetch repository
-        run: git fetch origin
-      - name: Abort if fork PR and dependency changes
-        if: github.event.pull_request.head.repo.full_name != github.repository
-        run: |
-          export DEPENDENCY_CHANGES=$(git diff origin/$GITHUB_BASE_REF --name-only -- reqs setup.cfg)
-          [[ -n ${DEPENDENCY_CHANGES} ]] &&
-            echo "Dependency changes:"
-            echo ${DEPENDENCY_CHANGES}
-            echo -e "\e[31;1mERROR: cannot modify package dependencies through a PR from a fork\e[0m" &&
-            exit 1
-      - name: Return success if no dependency changes
-        run: "[[ -z ${DEPENDENCY_CHANGES} ]] && exit 0"
       - name: Upgrade dependencies
+        if: steps.git-diff.outputs.dependency-changes != ''
         run: bash reqs/upgrade.sh
       - uses: actions/upload-artifact@v2
         with:
@@ -57,7 +64,7 @@ jobs:
     if: github.event.pull_request.draft == false
     runs-on: ubuntu-18.04
     needs:
-      - requirements
+      - upgrade
     steps:
       - uses: actions/checkout@v2
         with:
