fix: abort if fork PR and dependency changes

diff --git a/.github/workflows/requirements-pr.yml b/.github/workflows/requirements-pr.yml
--- a/.github/workflows/requirements-pr.yml
+++ b/.github/workflows/requirements-pr.yml
@@ -32,6 +32,13 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install pip-tools
+      - name: Abort if fork PR and dependency changes
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          git fetch origin
+          [[ $(git diff origin/$GITHUB_BASE_REF --name-only -- reqs setup.cfg) ]] &&
+            echo -e "\e[31;1mERROR: cannot modify package dependencies through a PR from a fork\e[0m" &&
+            exit 1
       - name: Upgrade dependencies
         run: |
           git fetch origin
